## Numpy Assignment

1. Import the Numpy package under the name np.

In [2]:
import numpy as np

2. Create a null vector of size 10.

In [3]:
null_v1 = np.zeros(10)
null_v1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a null vector of size 10 but the fifth value which is 1

In [4]:
null_v2 = np.zeros(10)
null_v2[4]=1
null_v2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

4. Create a vector with values ranging from 10 to 49

In [6]:
a = np.arange(10,49)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

5. Create a vector with values ranging from 10 to 49

In [7]:
reverse_a = a[::-1]
reverse_a

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

6. Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
m = np.arange(0,9).reshape(3,3)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7. Find indices of non­zero elements from [1,2,0,0,4,0]

In [10]:
b = [1,2,0,0,4,0]
np.nonzero(b)

(array([0, 1, 4], dtype=int64),)

8. Create a 3x3x3 array with random values

In [13]:
c = np.random.random((3,3,3))
c

array([[[0.79347504, 0.04859964, 0.15846673],
        [0.24410931, 0.47492107, 0.04952513],
        [0.10149929, 0.92371894, 0.33345256]],

       [[0.31822833, 0.54082106, 0.70919401],
        [0.55514702, 0.37253468, 0.66915524],
        [0.37267954, 0.63159704, 0.56655699]],

       [[0.54620269, 0.56237713, 0.22442669],
        [0.5872573 , 0.64107678, 0.65228944],
        [0.1943427 , 0.20615397, 0.60670762]]])

9. Create a random vector of size 30 and find the mean value.

In [16]:
v = np.random.random(30)
print(v)
print('\nMean:', v.mean())

[0.2873549  0.90699159 0.44442357 0.78902887 0.41487793 0.97466312
 0.23704836 0.92568657 0.49161908 0.96697068 0.16057638 0.08321593
 0.22439844 0.00167093 0.39513291 0.66211265 0.01573769 0.92779897
 0.84179774 0.05410474 0.90431608 0.1031871  0.06849228 0.06543467
 0.61713052 0.76408156 0.6787883  0.73096309 0.15652929 0.73914348]

Mean: 0.4877759138869294


10. Create a 2d array with 1 on the border and 0 inside

In [17]:
z = np.ones((10,10))
z[1:-1, 1:-1]=0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


11. Create an 8x8 matrix and fill it with a checkerboard pattern

In [19]:
x = np.zeros((8,8), dtype=int)
x[1::2, ::2]=1
x[::2, 1::2]=1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


12. What is the major difference between sets, lists, tuples, and dictionaries?

List is Ordered collection which allows dublicates

Sets is Unordered collection of items which doesn't takes dublicates value

Tuples is Ordered collection of items which are unchangable

Dictionary is a collection which is unordered, changeable and indexed.

13. Print first 10 natural numbers using while loop

In [20]:
i = 1
while(i<=10):
    print(i)
    i+=1

1
2
3
4
5
6
7
8
9
10


14. Print the numbers -10 to -1 using for loop.

In [21]:
for i in range(-10, 0):
    print(i)

-10
-9
-8
-7
-6
-5
-4
-3
-2
-1


15. Print the message “Done” after successful execution of any for loop.

In [22]:
for i in range(5):
    print(i)
print("DONE")

0
1
2
3
4
DONE


16. Create a random vector of size 10 and sort it

In [26]:
y = np.random.random(10)
print("Random vector is:", y)
y.sort()
print("\n Sorted vector is:", y)

Random vector is: [0.38216034 0.48608723 0.21845814 0.7642767  0.09505794 0.82579074
 0.32244705 0.72944795 0.01364872 0.7039773 ]

 Sorted vector is: [0.01364872 0.09505794 0.21845814 0.32244705 0.38216034 0.48608723
 0.7039773  0.72944795 0.7642767  0.82579074]


17. Execute any three math functions using numpy.

In [29]:
print("Sum of vector:", y.sum())
print("\nSquare root:", np.sqrt(y))
print("\nMean of vector:", y.mean())

Sum of vector: 4.541352112827095

Square root: [0.11682774 0.30831467 0.46739506 0.56784421 0.61819119 0.69719956
 0.83903355 0.85407725 0.8742292  0.90873029]

Mean of vector: 0.4541352112827095
